
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mirth.connect.connectors.ws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-09-16T15:23:45.898+07:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "DefaultAcceptMessageService",
                      portName = "DefaultAcceptMessagePort",
                      targetNamespace = "http://ws.connectors.connect.mirth.com/",
                      wsdlLocation = "http://120.72.83.85:8843/services/Mirth?wsdl",
                      endpointInterface = "com.mirth.connect.connectors.ws.DefaultAcceptMessage")
                      
public class DefaultAcceptMessagePortImpl implements DefaultAcceptMessage {

    private static final Logger LOG = Logger.getLogger(DefaultAcceptMessagePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mirth.connect.connectors.ws.DefaultAcceptMessage#acceptMessage(java.lang.String  arg0 )*
     */
    public java.lang.String acceptMessage(java.lang.String arg0) { 
        LOG.info("Executing operation acceptMessage");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-464007225";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
